// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9O6XT3l44xMxHmyag2AMBaY9fa6FxvXg',
    appId: '1:555986258926:web:0494535a3f557b47c3dcff',
    messagingSenderId: '555986258926',
    projectId: 'buzzapp-fa8e0',
    authDomain: 'buzzapp-fa8e0.firebaseapp.com',
    storageBucket: 'buzzapp-fa8e0.appspot.com',
    measurementId: 'G-XEQSGVNPX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_goBxDF2vgXqcRwVCsu7mRljp56nKPJY',
    appId: '1:555986258926:android:9eb4fc73bbe158cec3dcff',
    messagingSenderId: '555986258926',
    projectId: 'buzzapp-fa8e0',
    storageBucket: 'buzzapp-fa8e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGYt51yrJykLHrOK3n4Z7YytCXiFn0-RA',
    appId: '1:555986258926:ios:f6ad3d432e96f088c3dcff',
    messagingSenderId: '555986258926',
    projectId: 'buzzapp-fa8e0',
    storageBucket: 'buzzapp-fa8e0.appspot.com',
    iosClientId: '555986258926-89qsd4mfrjumfbtise71ijjd6c6vr6d3.apps.googleusercontent.com',
    iosBundleId: 'com.intecons.buzzapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGYt51yrJykLHrOK3n4Z7YytCXiFn0-RA',
    appId: '1:555986258926:ios:f6ad3d432e96f088c3dcff',
    messagingSenderId: '555986258926',
    projectId: 'buzzapp-fa8e0',
    storageBucket: 'buzzapp-fa8e0.appspot.com',
    iosClientId: '555986258926-89qsd4mfrjumfbtise71ijjd6c6vr6d3.apps.googleusercontent.com',
    iosBundleId: 'com.intecons.buzzapp',
  );
}
